### ISSUE TITLE
request to support HDS on apple watch

### ISSUE THREAD

**Issue by Tucd7v** [qe201020335/HRCounter#10]
the HDS repo :https://github.com/Rexios80/Health-Data-Server-Overlay
this one is kinda like HypeRate but is a paid software.

**Comment by qe201020335** [comment]
I will take a look, thanks for the request

**Comment by qe201020335** [comment]
I don't see they have an api for other program to get hr data from their application, so I can't officially support it.

With this being said, I am able to hack together a small program that can receive the data from apple watch. However, this will not work with their overlay, you can only use one at a time (since their watch app can only connect to one server). Making metter worse, since the way their app communicates with a server is not public documented, it may change in any future updates. Any changes in their internal api will basically break what I made.

I think you'd better request an api feature on their github repo, then I could officially support it via its public api.

If there is an api for their application that I somehow did not find, please comment it. Thanks!

**Comment by Tucd7v** [comment]
from what I known.HDS was able to send data to a local HDS server without using theirs cloud service. and relay data to other HDS servers. but as you said, I'm unable to find any API to use.
therefore I might just switch to hyperate cuz this software seems no different from HDS.
