### ISSUE TITLE
HRProxy was loaded when choose webrequest

### ISSUE THREAD

**Issue by roboltz** [qe201020335/HRCounter#24]
When playing a level the heart rate counter does not show, it does show when I go into the counters+ menu, I think it also might be interfering with the misses counter? It always shows 0 no matter how many times I miss. 
My config:
![HRCounter json_ - Microsoft Visual Studio 2_23_2022 1_57_25 PM](https://user-images.githubusercontent.com/77972303/155388668-1d72e024-d23b-4d83-8ca9-a36a60d2f856.png)
replaced (my name) just for the png.
It works fine displaying the heart rate to my PC, and even on obs.
My latest log: [_latest.log](https://github.com/qe201020335/HRCounter/files/8127061/_latest.log)

**Comment by roboltz** [comment]
Sorry, I think it was because I didn't have websocket-sharp installed.

**Comment by roboltz** [comment]
yep im an idiot

**Comment by qe201020335** [comment]
Yeah, the log did indicate that you did not install websocket-sharp.

However, since the data source you choose is `WebRequest`, websocket-sharp is not needed at all. This is also the reason I did not put websocket sharp as a required mod in the bsipa plugin meta json.

I need to look into this.
Why `HRProxy` was loaded when you choose webrequest?

**Comment by 200Tigersbloxed** [comment]
> Why `HRProxy` was loaded when you choose webrequest?

A very plausible cause could be the fact that the [`DataSource`](https://github.com/qe201020335/HRCounter/blob/master/HRCounter/Configuration/PluginConfig.cs#L14)'s value initializes at `Pulsoid`? Maybe something wacky is going on with the config and it's regenerating mid-map?

**Comment by qe201020335** [comment]
Fixed in this commit ca40849
