### ISSUE TITLE
HRCounter not appearing in levels

### ISSUE THREAD

**Issue by admiralamott1** [qe201020335/HRCounter#7]
Hey there,
Ive used HRCounter before, been a while since I used it again but I cant get it to appear in the levels anymore, they just dont show up.
To clarify, they appear in counters, I've sent my feed correctly (with the api feed link not the other one) reinstalled both counters and hrcounter and it doesn't seem to appear? 

I recorded a vid of what i see~: https://www.youtube.com/watch?v=-vyr-oZOW_A

Love your work btw :)

**Comment by qe201020335** [comment]
Could you upload the log file of the mod for that session in the video ? It is in `Beat Saber\Logs\HRCounter`.
And also, have you tried other counter locations? for example Below Combo or BelowMultiplier

**Comment by admiralamott1** [comment]
Hi, yes I tried above score and over highway and the problem persists.
Is this what you meant? (attached log)

**Comment by qe201020335** [comment]
I don't think replay to the email with attached file will upload the file here

**Comment by admiralamott1** [comment]
[2021.07.04.16.59.58.log.gz](https://github.com/qe201020335/HRCounter/files/6768839/2021.07.04.16.59.58.log.gz)
[2021.07.04.17.25.11.log](https://github.com/qe201020335/HRCounter/files/6768840/2021.07.04.17.25.11.log)
[_latest.log](https://github.com/qe201020335/HRCounter/files/6768841/_latest.log)


They all appear to be empty haha

**Comment by qe201020335** [comment]
These log files seem only shows that you boot the game and the mod is initialized. You have to upload a log file that during when the issue occurs, otherwise it won't contain anything useful. 

If these are the files that during when the issue occurs, then it means that the counter is not being created when you start a level. In this case, either your config about data source is not correct or the problem is in other mods.

If you don't mind, you can upload your config file so I can check it, just in case.
